name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'djlint' }}
    # permissions:
    #   id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: pipx run poetry build --no-interaction
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
  publish-npm:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'djlint' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
